import 'package:test_api/test_api.dart';
import 'package:zwe_companion/model/model.dart';

void main() {
  test('Test ZweDuration constructor', () {
    var duration1 = ZweDuration(0);
    var duration2 = ZweDuration(42);
    var duration3 = ZweDuration.fromTime(0, 0);
    var duration4 = ZweDuration.fromTime(4, 0);
    var duration5 = ZweDuration.fromTime(0, 12);
    var duration6 = ZweDuration.fromTime(4, 12);
    var duration7 = ZweDuration.fromTime(4, 15);
    var duration8 = ZweDuration.fromTime(6, 57);
    expect(duration1.raw, equals(0));
    expect(duration2.raw, equals(42));
    expect(duration3.raw, equals(0));
    expect(duration4.raw, equals(40));
    expect(duration5.raw, equals(2));
    expect(duration6.raw, equals(42));
    expect(duration7.raw, equals(42));
    expect(duration8.raw, equals(69));
  });
  test('Test ZweDuration hour and minute getters', () {
    var duration1 = ZweDuration.fromTime(0, 0);
    var duration2 = ZweDuration.fromTime(4, 0);
    var duration3 = ZweDuration.fromTime(0, 12);
    var duration4 = ZweDuration.fromTime(4, 12);
    var duration5 = ZweDuration.fromTime(4, 15);
    var duration6 = ZweDuration.fromTime(6, 57);
    expect(duration1.hour, equals(0));
    expect(duration1.minute, equals(0));
    expect(duration2.hour, equals(4));
    expect(duration2.minute, equals(0));
    expect(duration3.hour, equals(0));
    expect(duration3.minute, equals(12));
    expect(duration4.hour, equals(4));
    expect(duration4.minute, equals(12));
    expect(duration5.hour, equals(4));
    expect(duration5.minute, equals(12));
    expect(duration6.hour, equals(6));
    expect(duration6.minute, equals(54));
  });
  test('Test ZweDuration operators', () {
    expect(ZweDuration(5), equals(ZweDuration(5)));
    expect(ZweDuration(5) + ZweDuration(10), equals(ZweDuration(15)));
    expect(ZweDuration(10) + ZweDuration(5), equals(ZweDuration(15)));
    expect(-ZweDuration(5), equals(ZweDuration(-5)));
    expect(-ZweDuration(-5), equals(ZweDuration(5)));
    expect(ZweDuration(15) - ZweDuration(10), equals(ZweDuration(5)));
    expect(ZweDuration(10) - ZweDuration(15), equals(ZweDuration(-5)));
    expect(ZweDuration(10).abs(), ZweDuration(10));
    expect(ZweDuration(-10).abs(), ZweDuration(10));
    expect(ZweDuration(10).isNegative(), false);
    expect(ZweDuration(-10).isNegative(), true);
    expect(ZweDuration(10).isPositive(), true);
    expect(ZweDuration(-10).isPositive(), false);
  });
  test('Test ZweInstant constructor', () {
    var instant1 = ZweInstant(0);
    var instant2 = ZweInstant(42);
    var instant3 = ZweInstant.fromTime(0, 0);
    var instant4 = ZweInstant.fromTime(4, 0);
    var instant5 = ZweInstant.fromTime(0, 12);
    var instant6 = ZweInstant.fromTime(4, 12);
    var instant7 = ZweInstant.fromTime(4, 15);
    var instant8 = ZweInstant.fromTime(6, 57);
    expect(instant1.raw, equals(0));
    expect(instant2.raw, equals(42));
    expect(instant3.raw, equals(175));
    expect(instant4.raw, equals(215));
    expect(instant5.raw, equals(177));
    expect(instant6.raw, equals(217));
    expect(instant7.raw, equals(217));
    expect(instant8.raw, equals(4));
  });
  test('Test ZweInstant getters', () {
    var instant1 = ZweInstant.fromTime(0, 0);
    var instant2 = ZweInstant.fromTime(4, 0);
    var instant3 = ZweInstant.fromTime(0, 12);
    var instant4 = ZweInstant.fromTime(4, 12);
    var instant5 = ZweInstant.fromTime(4, 15);
    var instant6 = ZweInstant.fromTime(6, 57);
    var instant7 = ZweInstant(275);
    expect(instant1.hour, equals(0));
    expect(instant1.minute, equals(0));
    expect(instant2.hour, equals(4));
    expect(instant2.minute, equals(0));
    expect(instant3.hour, equals(0));
    expect(instant3.minute, equals(12));
    expect(instant4.hour, equals(4));
    expect(instant4.minute, equals(12));
    expect(instant5.hour, equals(4));
    expect(instant5.minute, equals(12));
    expect(instant6.hour, equals(6));
    expect(instant6.minute, equals(54));
    expect(instant6.dayOffset, equals(0));
    expect(instant7.dayOffset, equals(1));
    expect(instant7.hour, equals(10));
    expect(instant7.minute, equals(0));
  });
  test('Test ZweInstant operators', () {
    expect(ZweInstant(5), equals(ZweInstant(5)));
    expect(ZweInstant(5) + ZweDuration(10), equals(ZweInstant(15)));
    expect(ZweInstant(10) + ZweDuration(5), equals(ZweInstant(15)));
    expect(ZweInstant(15) - ZweDuration(5), equals(ZweInstant(10)));
    expect(ZweInstant(15) - ZweDuration(10), equals(ZweInstant(5)));
    expect(ZweInstant(10).until(ZweInstant(20)), ZweDuration(10));
    expect(ZweInstant(230).until(ZweInstant(20)), ZweDuration(30));
  });
}