# See: https://medium.com/flutter-io/test-flutter-apps-on-travis-3fd5142ecd8c
os:
  - linux
sudo: false
addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
    - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
    - libstdc++6
    - lib32stdc++6
    - fonts-droid
before_script:
  - git clone https://github.com/flutter/flutter.git -b beta ../flutter -b beta --depth 1
  - ../flutter/bin/flutter doctor
  # check if files are formatted according to dartfmt
  - $(../flutter/bin/cache/dart-sdk/bin/dartfmt -n lib)
  # static code analysis
  - ../flutter/bin/flutter analyze
  # installing coveralls add-on
  - gem install coveralls-lcov
script:
  # run tests with coverage
  - ../flutter/bin/flutter test --coverage test/*
after_success:
  # evaluate coverage
  - coveralls-lcov coverage/lcov.info
cache:
  directories:
  - $HOME/.pub-cache
